apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::448465605637:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K2AEY3AP9L2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      -system:masters
      rolearn: arn:aws:iam::448465605637:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-04T20:41:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1615"
  uid: 801e2c79-3580-4ea5-9c66-4db9b112862c
